sudo: required
language: python
services:
- docker
python:
- '3.6'
before_script:
- docker-compose build
script:
- echo "done"
#- docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py &&
#  ./manage.py test"
after_success:
#- if [ "$TRAVIS_BRANCH" == "master" ];
#  then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
#  registry.heroku.com; docker tag web registry.heroku.com/MSBlog-prod/web; docker
#  push registry.heroku.com/MSBlog-prod/web;
#  fi
#- if [ "$TRAVIS_BRANCH" == "qa" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
#  registry.heroku.com; docker tag web registry.heroku.com/MSBlog-qa/web; docker push
#  registry.heroku.com/MSBlog-qa/web; fi
notifications:
  email: false
cache:
  pip: true
before_install:
- openssl aes-256-cbc -K $encrypted_26e1cd2596af_key -iv $encrypted_26e1cd2596af_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts: 101.132.121.41