# Generated by Django 2.0.8 on 2018-08-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='father_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Directory'),
        ),
        migrations.AddField(
            model_name='directory',
            name='name',
            field=models.CharField(db_index=True, default='你妈死了', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Directory'),
        ),
    ]
