# Generated by Django 2.0.8 on 2018-08-21 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180821_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='id',
        ),
        migrations.AddField(
            model_name='directory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(db_index=True, default='你妈死了', max_length=20),
            preserve_default=False,
        ),
    ]
