# Generated by Django 2.0.8 on 2018-08-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180822_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='father_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_directories', to='blog.Directory'),
        ),
    ]
