# Generated by Django 2.0.8 on 2018-10-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180823_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='related_posts',
            field=models.IntegerField(default=0),
        ),
    ]
