# Generated by Django 2.0.8 on 2018-10-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
